/**
 * Draw a finite Fourier sample from a real-valued Gaussian process on the 2D torus
 * generated by the translation lattice, optionally symmetrized under the point group
 * of a wallpaper group.
 *
 * Approach:
 *   1. Compute dual-lattice vectors k1, k2 from the translation lattice v1, v2.
 *   2. For each frequency pair (n1, n2) in a half-plane, draw random Fourier
 *      coefficients weighted by a spectral envelope (squared-exponential).
 *   3. Evaluate the GP as a Fourier sum: f(r) = Σ [a cos(k·r) + b sin(k·r)].
 *   4. To make the GP invariant under a wallpaper group, average f over the
 *      distinct point-group elements (unique linear parts of the isometries).
 */

/* ---------- Seedable PRNG (mulberry32) ----------------------------------- */

function mulberry32(seed) {
  let s = seed | 0;
  return function () {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ---------- Box-Muller normal random ------------------------------------- */

function randn(rng) {
  let u1;
  do {
    u1 = rng();
  } while (u1 === 0);
  const u2 = rng();
  return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

/* ---------- Dual lattice ------------------------------------------------- */

/**
 * Compute dual lattice vectors k1, k2 such that vi · kj = 2π δij.
 *
 * Given column-stacked matrix V = [v1 | v2], we need K = 2π (V^T)^{-1}.
 */
export function computeDualLattice(v1, v2) {
  const det = v1.x * v2.y - v1.y * v2.x;
  const inv = (2 * Math.PI) / det;
  return {
    k1: { x: v2.y * inv, y: -v2.x * inv },
    k2: { x: -v1.y * inv, y: v1.x * inv },
  };
}

/* ---------- Fourier coefficients ----------------------------------------- */

/**
 * Draw random Fourier coefficients for a GP on the torus.
 *
 * @param {{v1:{x,y}, v2:{x,y}}} latticeVectors  Translation lattice basis.
 * @param {number} seed          Integer seed for the PRNG.
 * @param {number} [maxFreq=5]   Max absolute frequency index in each direction.
 * @param {number} [lengthScale=0.6]  Length scale for the spectral envelope.
 * @returns {{ modes: Array<{kx,ky,a,b}>, dc: number }}
 */
export function drawGPCoefficients(
  latticeVectors,
  seed,
  maxFreq = 5,
  lengthScale = 0.6
) {
  const rng = mulberry32(seed);
  const { k1, k2 } = computeDualLattice(
    latticeVectors.v1,
    latticeVectors.v2
  );

  const modes = [];
  for (let n1 = -maxFreq; n1 <= maxFreq; n1++) {
    for (let n2 = -maxFreq; n2 <= maxFreq; n2++) {
      if (n1 === 0 && n2 === 0) continue;
      // Half-plane: keep (n1 > 0) or (n1 === 0 && n2 > 0)
      if (n1 < 0 || (n1 === 0 && n2 < 0)) continue;

      const kx = n1 * k1.x + n2 * k2.x;
      const ky = n1 * k1.y + n2 * k2.y;
      const k2mag = kx * kx + ky * ky;
      // Squared-exponential spectral envelope
      const sigma = Math.exp((-k2mag * lengthScale * lengthScale) / 4);

      const a = randn(rng) * sigma;
      const b = randn(rng) * sigma;

      modes.push({ kx, ky, a, b });
    }
  }

  const dc = randn(rng) * 0.1;
  return { modes, dc };
}

/* ---------- GP evaluation ------------------------------------------------ */

/**
 * Evaluate the (unsymmetrized) GP at a point.
 */
export function evaluateGP(gpCoeffs, x, y) {
  let val = gpCoeffs.dc;
  for (const { kx, ky, a, b } of gpCoeffs.modes) {
    const phase = kx * x + ky * y;
    val += a * Math.cos(phase) + b * Math.sin(phase);
  }
  return val;
}

/* ---------- Point-group extraction --------------------------------------- */

/**
 * Extract point-group representatives from the generated wallpaper-group
 * elements.  Two elements belong to the same coset of the translation
 * subgroup iff they share the same linear part (a, b, c, d).  We return
 * one full isometry per coset so the translation component is available
 * for the symmetrization average.
 */
export function extractPointGroup(elements) {
  const EPS = 1e-6;
  const reps = [];
  for (const el of elements) {
    const dup = reps.some(
      (u) =>
        Math.abs(u.a - el.a) < EPS &&
        Math.abs(u.b - el.b) < EPS &&
        Math.abs(u.c - el.c) < EPS &&
        Math.abs(u.d - el.d) < EPS
    );
    if (!dup) reps.push(el);
  }
  return reps;
}

/* ---------- Symmetrized evaluation --------------------------------------- */

/**
 * Evaluate the GP symmetrized under the point group.
 *
 * f_sym(r) = (1/|P|) Σ_{g ∈ P} f(g(r))
 *
 * Because f is already periodic under the lattice, f(g(r)) = f(R r + t)
 * is independent of which coset representative we chose (up to a lattice
 * translation, which doesn't change f).
 */
function evaluateSymmetrizedGP(gpCoeffs, x, y, pointGroup) {
  let sum = 0;
  for (const g of pointGroup) {
    const gx = g.a * x + g.b * y + g.tx;
    const gy = g.c * x + g.d * y + g.ty;
    sum += evaluateGP(gpCoeffs, gx, gy);
  }
  return sum / pointGroup.length;
}

/* ---------- Heatmap generation ------------------------------------------- */

/**
 * Generate a 2D grid of symmetrized-GP values for heatmap rendering.
 *
 * @param {object} gpCoeffs       Output of drawGPCoefficients.
 * @param {Array}  pointGroup     Output of extractPointGroup.
 * @param {{minX,maxX,minY,maxY}} bounds  Math-coordinate bounding box.
 * @param {number} [resolution=100]  Grid cells along each axis.
 * @returns {{ data: number[][], minVal: number, maxVal: number, resolution: number }}
 */
export function generateGPHeatmap(
  gpCoeffs,
  pointGroup,
  bounds,
  resolution = 100
) {
  const { minX, maxX, minY, maxY } = bounds;
  const dx = (maxX - minX) / resolution;
  const dy = (maxY - minY) / resolution;

  const data = [];
  let minVal = Infinity;
  let maxVal = -Infinity;

  for (let j = 0; j < resolution; j++) {
    const row = [];
    // Row 0 → top of image → maxY
    const y = maxY - (j + 0.5) * dy;
    for (let i = 0; i < resolution; i++) {
      const x = minX + (i + 0.5) * dx;
      const val = evaluateSymmetrizedGP(gpCoeffs, x, y, pointGroup);
      row.push(val);
      if (val < minVal) minVal = val;
      if (val > maxVal) maxVal = val;
    }
    data.push(row);
  }

  return { data, minVal, maxVal, resolution };
}

/* ---------- Canvas rendering --------------------------------------------- */

/**
 * Render a GP heatmap to a data-URL string (PNG) suitable for an SVG
 * <image> element.
 *
 * Uses a blue → white → red diverging color map centered on the midpoint.
 *
 * @param {{ data, minVal, maxVal, resolution }} heatmap
 * @returns {string|null}  data:image/png;base64,… URL, or null in
 *   environments that lack canvas support (e.g. jsdom in tests).
 */
export function heatmapToDataURL(heatmap) {
  const { data, minVal, maxVal, resolution } = heatmap;
  const range = maxVal - minVal || 1;

  const canvas =
    typeof OffscreenCanvas !== 'undefined'
      ? new OffscreenCanvas(resolution, resolution)
      : document.createElement('canvas');
  canvas.width = resolution;
  canvas.height = resolution;
  const ctx = canvas.getContext('2d');
  const imgData = ctx.createImageData(resolution, resolution);

  for (let j = 0; j < resolution; j++) {
    for (let i = 0; i < resolution; i++) {
      const t = (data[j][i] - minVal) / range; // 0..1
      // Diverging: blue (t=0) → white (t=0.5) → red (t=1)
      let r, g, b;
      if (t < 0.5) {
        const s = t * 2; // 0..1
        r = Math.round(s * 255);
        g = Math.round(s * 255);
        b = 255;
      } else {
        const s = (t - 0.5) * 2; // 0..1
        r = 255;
        g = Math.round((1 - s) * 255);
        b = Math.round((1 - s) * 255);
      }
      const idx = (j * resolution + i) * 4;
      imgData.data[idx] = r;
      imgData.data[idx + 1] = g;
      imgData.data[idx + 2] = b;
      imgData.data[idx + 3] = 255;
    }
  }

  ctx.putImageData(imgData, 0, 0);

  // OffscreenCanvas has no toDataURL, so fall back to a regular canvas when
  // running in tests (Node / jsdom) that provide neither.
  if (typeof canvas.toDataURL === 'function') {
    return canvas.toDataURL();
  }
  // OffscreenCanvas path – convertToBlob is async, but we need sync.
  // Prefer the regular-canvas path above.  In environments that lack
  // both (e.g. jsdom in tests), return null and let callers handle it.
  return null;
}
