/**
 * Draw a finite Fourier sample from a real-valued Gaussian process on the 2D torus
 * generated by the translation lattice, optionally symmetrized under the point group
 * of a wallpaper group.
 *
 * Approach:
 *   1. Compute dual-lattice vectors k1, k2 from the translation lattice v1, v2.
 *   2. For each frequency pair (n1, n2) in a half-plane, draw random Fourier
 *      coefficients weighted by a spectral envelope (squared-exponential).
 *   3. Evaluate the GP as a Fourier sum: f(r) = Σ [a cos(k·r) + b sin(k·r)].
 *   4. To make the GP invariant under a wallpaper group, average f over the
 *      distinct point-group elements (unique linear parts of the isometries).
 */

/* ---------- Seedable PRNG (mulberry32) ----------------------------------- */

function mulberry32(seed) {
  let s = seed | 0;
  return function () {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ---------- Box-Muller normal random ------------------------------------- */

function randn(rng) {
  let u1;
  do {
    u1 = rng();
  } while (u1 === 0);
  const u2 = rng();
  return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

/* ---------- Dual lattice ------------------------------------------------- */

/**
 * Compute dual lattice vectors k1, k2 such that vi · kj = 2π δij.
 *
 * Given column-stacked matrix V = [v1 | v2], we need K = 2π (V^T)^{-1}.
 */
export function computeDualLattice(v1, v2) {
  const det = v1.x * v2.y - v1.y * v2.x;
  const inv = (2 * Math.PI) / det;
  return {
    k1: { x: v2.y * inv, y: -v2.x * inv },
    k2: { x: -v1.y * inv, y: v1.x * inv },
  };
}

/* ---------- Fourier coefficients ----------------------------------------- */

/**
 * Draw random Fourier coefficients for a GP on the torus.
 *
 * @param {{v1:{x,y}, v2:{x,y}}} latticeVectors  Translation lattice basis.
 * @param {number} seed          Integer seed for the PRNG.
 * @param {number} [maxFreq=5]   Max absolute frequency index in each direction.
 * @param {number} [lengthScale=0.1]  Length scale for the spectral envelope.
 * @returns {{ modes: Array<{kx,ky,a,b,envelope}>, dc: number, dcEnvelope: number }}
 */
export function drawGPCoefficients(
  latticeVectors,
  seed,
  maxFreq = 5,
  lengthScale = 0.1
) {
  const rng = mulberry32(seed);
  const { k1, k2 } = computeDualLattice(
    latticeVectors.v1,
    latticeVectors.v2
  );

  const modes = [];
  for (let n1 = -maxFreq; n1 <= maxFreq; n1++) {
    for (let n2 = -maxFreq; n2 <= maxFreq; n2++) {
      if (n1 === 0 && n2 === 0) continue;
      // Half-plane: keep (n1 > 0) or (n1 === 0 && n2 > 0)
      if (n1 < 0 || (n1 === 0 && n2 < 0)) continue;

      const kx = n1 * k1.x + n2 * k2.x;
      const ky = n1 * k1.y + n2 * k2.y;
      const k2mag = kx * kx + ky * ky;
      // Squared-exponential spectral envelope
      const envelope = Math.exp((-k2mag * lengthScale * lengthScale) / 4);

      const a = randn(rng) * envelope;
      const b = randn(rng) * envelope;

      modes.push({ kx, ky, a, b, envelope });
    }
  }

  const dc = randn(rng) * 0.1;
  return { modes, dc, dcEnvelope: 0.1 };
}

/* ---------- Ornstein–Uhlenbeck step -------------------------------------- */

/**
 * Advance GP coefficients by one Ornstein–Uhlenbeck step.
 *
 * Each Fourier coefficient (a, b) and the DC offset evolve as independent
 * OU processes with mean 0 and stationary variance equal to their original
 * envelope².  This preserves the same stationary distribution as
 * drawGPCoefficients.
 *
 * Discrete update:
 *   X(t+Δt) = ρ X(t) + envelope √(1 − ρ²) Z,   Z ~ N(0,1)
 * where ρ = decayFactor = exp(−θ Δt).
 *
 * @param {{ modes: Array<{kx,ky,a,b,envelope}>, dc: number, dcEnvelope: number }} gpCoeffs
 * @param {number} decayFactor  exp(−speed × dt), in [0, 1].
 * @returns {{ modes: Array<{kx,ky,a,b,envelope}>, dc: number, dcEnvelope: number }}
 */
export function ouStepGPCoefficients(gpCoeffs, decayFactor) {
  const rho = Math.min(Math.max(decayFactor, 0), 1);
  const noiseScale = Math.sqrt(Math.max(0, 1 - rho * rho));

  const newModes = gpCoeffs.modes.map((m) => ({
    kx: m.kx,
    ky: m.ky,
    envelope: m.envelope,
    a: m.a * rho + m.envelope * noiseScale * randn(Math.random),
    b: m.b * rho + m.envelope * noiseScale * randn(Math.random),
  }));

  const dcEnv = gpCoeffs.dcEnvelope ?? 0.1;
  const newDc = gpCoeffs.dc * rho + dcEnv * noiseScale * randn(Math.random);

  return { modes: newModes, dc: newDc, dcEnvelope: dcEnv };
}

/* ---------- Stochastic harmonic oscillator step -------------------------- */

/**
 * Compute the matrix exponential M = exp(A·dt) for the 2D SHO system
 *   A = [[0, 1], [-ω², -2ζω]]
 * Handles underdamped (ζ<1), critically damped (ζ≈1), and overdamped (ζ>1).
 */
function shoMatrixExp(dt, omega, damping) {
  const alpha = damping * omega;
  const eadt = Math.exp(-alpha * dt);

  if (damping < 1 - 1e-6) {
    // Underdamped
    const omega_d = omega * Math.sqrt(1 - damping * damping);
    const cos_wd = Math.cos(omega_d * dt);
    const sin_wd = Math.sin(omega_d * dt);
    return {
      M11: eadt * (cos_wd + (alpha / omega_d) * sin_wd),
      M12: eadt * sin_wd / omega_d,
      M21: -eadt * (omega * omega / omega_d) * sin_wd,
      M22: eadt * (cos_wd - (alpha / omega_d) * sin_wd),
    };
  } else if (damping > 1 + 1e-6) {
    // Overdamped
    const omega_d = omega * Math.sqrt(damping * damping - 1);
    const cosh_wd = Math.cosh(omega_d * dt);
    const sinh_wd = Math.sinh(omega_d * dt);
    return {
      M11: eadt * (cosh_wd + (alpha / omega_d) * sinh_wd),
      M12: eadt * sinh_wd / omega_d,
      M21: -eadt * (omega * omega / omega_d) * sinh_wd,
      M22: eadt * (cosh_wd - (alpha / omega_d) * sinh_wd),
    };
  } else {
    // Critically damped
    return {
      M11: eadt * (1 + alpha * dt),
      M12: eadt * dt,
      M21: -eadt * omega * omega * dt,
      M22: eadt * (1 - alpha * dt),
    };
  }
}

/**
 * Apply one exact SHO step to a single (position, velocity) pair.
 *
 * Uses Q = Σ_∞ − M Σ_∞ M^T for the noise covariance, where
 *   Σ_∞ = diag(envelope², ω²·envelope²)
 * is the stationary covariance (X and V are uncorrelated).
 */
function shoStep1D(x, v, M11, M12, M21, M22, envelope, omega) {
  // Deterministic part
  const newX0 = M11 * x + M12 * v;
  const newV0 = M21 * x + M22 * v;

  // Stationary covariance
  const varX = envelope * envelope;
  const varV = omega * omega * varX;

  // Noise covariance Q = Σ_∞ − M Σ_∞ M^T
  const q11 = varX - (M11 * M11 * varX + M12 * M12 * varV);
  const q12 = -(M11 * M21 * varX + M12 * M22 * varV);
  const q22 = varV - (M21 * M21 * varX + M22 * M22 * varV);

  // Cholesky decomposition Q = L L^T
  const L11 = Math.sqrt(Math.max(0, q11));
  const L21 = L11 > 1e-15 ? q12 / L11 : 0;
  const L22 = Math.sqrt(Math.max(0, q22 - L21 * L21));

  const z1 = randn(Math.random);
  const z2 = randn(Math.random);

  return {
    x: newX0 + L11 * z1,
    v: newV0 + L21 * z1 + L22 * z2,
  };
}

/**
 * Advance GP coefficients by one stochastic harmonic oscillator (SHO) step.
 *
 * Each Fourier coefficient (a, b) and DC offset evolve as independent
 * underdamped Langevin oscillators:
 *   dX = V dt
 *   dV = −ω² X dt − 2ζω V dt + σ dW
 *
 * with σ chosen so that the stationary marginal for X is N(0, envelope²),
 * preserving the same stationary distribution as drawGPCoefficients.
 *
 * Uses the exact discrete-time solution via matrix exponential and
 * noise covariance Q = Σ_∞ − M Σ_∞ M^T.
 *
 * @param {object} gpCoeffs  Current state (modes with optional va/vb velocities)
 * @param {number} dt        Time step in seconds
 * @param {number} omega     Natural frequency (animation speed)
 * @param {number} damping   Damping ratio ζ (ζ < 1 underdamped, ζ ≥ 1 overdamped; clamped to min 1e-4)
 * @returns {object} Updated gpCoeffs with new positions and velocities
 */
export function shoStepGPCoefficients(gpCoeffs, dt, omega, damping) {
  const zeta = Math.max(damping, 1e-4);
  const { M11, M12, M21, M22 } = shoMatrixExp(dt, omega, zeta);

  const newModes = gpCoeffs.modes.map((m) => {
    const { x: newA, v: newVa } = shoStep1D(
      m.a, m.va ?? 0, M11, M12, M21, M22, m.envelope, omega
    );
    const { x: newB, v: newVb } = shoStep1D(
      m.b, m.vb ?? 0, M11, M12, M21, M22, m.envelope, omega
    );
    return {
      kx: m.kx, ky: m.ky, envelope: m.envelope,
      a: newA, b: newB, va: newVa, vb: newVb,
    };
  });

  const dcEnv = gpCoeffs.dcEnvelope ?? 0.1;
  const { x: newDc, v: newVdc } = shoStep1D(
    gpCoeffs.dc, gpCoeffs.vdc ?? 0, M11, M12, M21, M22, dcEnv, omega
  );

  return { modes: newModes, dc: newDc, vdc: newVdc, dcEnvelope: dcEnv };
}

/* ---------- Wind (vector-field) coefficients ----------------------------- */

/**
 * Draw random Fourier coefficients for two independent GPs, used to build
 * an equivariant vector field for the wind-map mode.
 *
 * Both GPs share the same lattice and spectral envelope but receive
 * independent random draws (offset seeds).
 */
export function drawWindCoefficients(latticeVectors, seed, maxFreq = 5, lengthScale = 0.1) {
  return {
    gp1: drawGPCoefficients(latticeVectors, seed, maxFreq, lengthScale),
    gp2: drawGPCoefficients(latticeVectors, seed + 1000, maxFreq, lengthScale),
  };
}

/**
 * Advance both GP components of a wind field by one SHO step.
 */
export function shoStepWindCoefficients(windCoeffs, dt, omega, damping) {
  return {
    gp1: shoStepGPCoefficients(windCoeffs.gp1, dt, omega, damping),
    gp2: shoStepGPCoefficients(windCoeffs.gp2, dt, omega, damping),
  };
}

/* ---------- p3 equivariant (3-GP → RGB) coefficients --------------------- */

/**
 * Draw random Fourier coefficients for three independent GPs, used to build
 * a p3-equivariant R³-valued field via cyclic-permutation Reynolds averaging.
 *
 * All three GPs share the same lattice and spectral envelope but receive
 * independent random draws (offset seeds).
 */
export function drawP3Coefficients(latticeVectors, seed, maxFreq = 5, lengthScale = 0.1) {
  return {
    gp1: drawGPCoefficients(latticeVectors, seed, maxFreq, lengthScale),
    gp2: drawGPCoefficients(latticeVectors, seed + 1000, maxFreq, lengthScale),
    gp3: drawGPCoefficients(latticeVectors, seed + 2000, maxFreq, lengthScale),
  };
}

/**
 * Advance all three GP components of a p3 field by one SHO step.
 */
export function shoStepP3Coefficients(p3Coeffs, dt, omega, damping) {
  return {
    gp1: shoStepGPCoefficients(p3Coeffs.gp1, dt, omega, damping),
    gp2: shoStepGPCoefficients(p3Coeffs.gp2, dt, omega, damping),
    gp3: shoStepGPCoefficients(p3Coeffs.gp3, dt, omega, damping),
  };
}

/* ---------- GP evaluation ------------------------------------------------ */

/**
 * Evaluate the (unsymmetrized) GP at a point.
 */
export function evaluateGP(gpCoeffs, x, y) {
  let val = gpCoeffs.dc;
  for (const { kx, ky, a, b } of gpCoeffs.modes) {
    const phase = kx * x + ky * y;
    val += a * Math.cos(phase) + b * Math.sin(phase);
  }
  return val;
}

/* ---------- Point-group extraction --------------------------------------- */

/**
 * Extract point-group representatives from the generated wallpaper-group
 * elements.  Two elements belong to the same coset of the translation
 * subgroup iff they share the same linear part (a, b, c, d).  We return
 * one full isometry per coset so the translation component is available
 * for the symmetrization average.
 */
export function extractPointGroup(elements) {
  const EPS = 1e-6;
  const reps = [];
  for (const el of elements) {
    const dup = reps.some(
      (u) =>
        Math.abs(u.a - el.a) < EPS &&
        Math.abs(u.b - el.b) < EPS &&
        Math.abs(u.c - el.c) < EPS &&
        Math.abs(u.d - el.d) < EPS
    );
    if (!dup) reps.push(el);
  }
  return reps;
}

/* ---------- Symmetrized evaluation --------------------------------------- */

/**
 * Evaluate the GP symmetrized under the point group.
 *
 * Invariant mode (default):
 *   f_sym(r) = (1/|P|) Σ_{g ∈ P} f(g(r))
 *
 * Equivariant mode (only valid for |P| = 2):
 *   f_sym(r) = (1/2) [f(r) − f(g(r))]
 *   where g is the non-identity coset representative.
 *
 * Because f is already periodic under the lattice, f(g(r)) = f(R r + t)
 * is independent of which coset representative we chose (up to a lattice
 * translation, which doesn't change f).
 */
function evaluateSymmetrizedGP(gpCoeffs, x, y, pointGroup, equivariant = false) {
  let sum = 0;
  for (let i = 0; i < pointGroup.length; i++) {
    const g = pointGroup[i];
    const gx = g.a * x + g.b * y + g.tx;
    const gy = g.c * x + g.d * y + g.ty;
    const sign = (equivariant && i > 0) ? -1 : 1;
    sum += sign * evaluateGP(gpCoeffs, gx, gy);
  }
  return sum / pointGroup.length;
}

/* ---------- p3 equivariant evaluation ------------------------------------ */

/**
 * Evaluate the p3-equivariant vector field F: R² → R³ at a point.
 *
 * Uses three independent GPs and Reynolds averaging with the cyclic
 * permutation representation of C₃:
 *
 *   F_c(r) = (1/3) Σ_{g=0}^{2} f_{(c+g) mod 3}(g(r))
 *
 * where g indexes the point-group cosets {e, r₁₂₀, r₂₄₀}.
 *
 * @param {object} gp1  First GP coefficients
 * @param {object} gp2  Second GP coefficients
 * @param {object} gp3  Third GP coefficients
 * @param {number} x    x-coordinate
 * @param {number} y    y-coordinate
 * @param {Array}  pointGroup  [{a,b,c,d,tx,ty}, ...] for the 3 coset reps
 * @returns {number[]}  [R, G, B] values (unnormalized)
 */
export function evaluateP3Equivariant(gp1, gp2, gp3, x, y, pointGroup) {
  const gps = [gp1, gp2, gp3];
  const n = pointGroup.length;
  const rgb = [0, 0, 0];
  for (let gi = 0; gi < n; gi++) {
    const g = pointGroup[gi];
    const gx = g.a * x + g.b * y + g.tx;
    const gy = g.c * x + g.d * y + g.ty;
    const vals = gps.map((gp) => evaluateGP(gp, gx, gy));
    const shift = gi % 3;
    for (let c = 0; c < 3; c++) {
      rgb[c] += vals[(c + shift) % 3];
    }
  }
  return rgb.map((v) => v / n);
}

/* ---------- Heatmap generation ------------------------------------------- */

/**
 * Generate a 2D grid of symmetrized-GP values for heatmap rendering.
 *
 * @param {object} gpCoeffs       Output of drawGPCoefficients.
 * @param {Array}  pointGroup     Output of extractPointGroup.
 * @param {{minX,maxX,minY,maxY}} bounds  Math-coordinate bounding box.
 * @param {number} [resolution=100]  Grid cells along each axis.
 * @param {boolean} [equivariant=false]  If true and |pointGroup|=2, use f−f∘g.
 * @returns {{ data: number[][], minVal: number, maxVal: number, resolution: number }}
 */
export function generateGPHeatmap(
  gpCoeffs,
  pointGroup,
  bounds,
  resolution = 100,
  equivariant = false
) {
  const { minX, maxX, minY, maxY } = bounds;
  const dx = (maxX - minX) / resolution;
  const dy = (maxY - minY) / resolution;

  const data = [];
  let minVal = Infinity;
  let maxVal = -Infinity;

  for (let j = 0; j < resolution; j++) {
    const row = [];
    // Row 0 → top of image → maxY
    const y = maxY - (j + 0.5) * dy;
    for (let i = 0; i < resolution; i++) {
      const x = minX + (i + 0.5) * dx;
      const val = evaluateSymmetrizedGP(gpCoeffs, x, y, pointGroup, equivariant);
      row.push(val);
      if (val < minVal) minVal = val;
      if (val > maxVal) maxVal = val;
    }
    data.push(row);
  }

  return { data, minVal, maxVal, resolution };
}

/* ---------- Canvas rendering --------------------------------------------- */

/**
 * Render a GP heatmap to a data-URL string (PNG) suitable for an SVG
 * <image> element.
 *
 * Uses a blue → white → red diverging color map centered on the midpoint.
 *
 * @param {{ data, minVal, maxVal, resolution }} heatmap
 * @returns {string|null}  data:image/png;base64,… URL, or null in
 *   environments that lack canvas support (e.g. jsdom in tests).
 */
export function heatmapToDataURL(heatmap) {
  const { data, minVal, maxVal, resolution } = heatmap;
  const range = maxVal - minVal || 1;

  // Prefer a regular <canvas> element (has synchronous toDataURL).
  // Fall back to OffscreenCanvas only when document is unavailable.
  let canvas;
  if (typeof document !== 'undefined') {
    canvas = document.createElement('canvas');
  } else if (typeof OffscreenCanvas !== 'undefined') {
    canvas = new OffscreenCanvas(resolution, resolution);
  } else {
    return null; // no canvas support (e.g. jsdom in tests)
  }
  canvas.width = resolution;
  canvas.height = resolution;
  const ctx = canvas.getContext('2d');
  const imgData = ctx.createImageData(resolution, resolution);

  for (let j = 0; j < resolution; j++) {
    for (let i = 0; i < resolution; i++) {
      const t = (data[j][i] - minVal) / range; // 0..1
      // Diverging: blue (t=0) → white (t=0.5) → red (t=1)
      let r, g, b;
      if (t < 0.5) {
        const s = t * 2; // 0..1
        r = Math.round(s * 255);
        g = Math.round(s * 255);
        b = 255;
      } else {
        const s = (t - 0.5) * 2; // 0..1
        r = 255;
        g = Math.round((1 - s) * 255);
        b = Math.round((1 - s) * 255);
      }
      const idx = (j * resolution + i) * 4;
      imgData.data[idx] = r;
      imgData.data[idx + 1] = g;
      imgData.data[idx + 2] = b;
      imgData.data[idx + 3] = 255;
    }
  }

  ctx.putImageData(imgData, 0, 0);

  if (typeof canvas.toDataURL === 'function') {
    return canvas.toDataURL();
  }
  return null;
}
